### PR TITLE
Fix #44 and proper handling of list of objects

### LINKED ISSUE #44: Errors on list of objects
When I try to parse a list of objects I get this error:

```bash
[error] java.lang.Error: "]":4:5 ..."{\n      id"
[error] at org.akkajs.shocon.package$Config$.apply(SHocon.scala:61)
[error] at org.akkajs.ConfigMacroLoader$.parse(ConfigMacroLoader.scala:88)
```

example:
```
{
  dataSource  = "weather-underground"
  normalizers = [
    {
      id              = "weather-underground_hourly_weather_forcast_retrieved_1"
      streamName      = "hourly_weather_forcast_retrieved"
      outputEventType = "hourly_weather_forcast_retrieved"
      versions        = ["0.1"]
      dir             = "0.1"
      trait           = "RawMessageNormalizerStreamService"
    },
    {
      id              = "my-data-source_2"
      streamName      = "data_retrieved"
      outputEventType = "data_retrieved"
      versions        = ["0.1"]
      dir             = "0.1"
      trait           = "RawMessageNormalizerStreamService"
    },
  ]
}
```

### PR DESCRIPTION
**Pull request by andreaTP**
Issue #44 actually opened a can of worm in lists management :smile: 

this is a fix that I tested working with the proposed use-case.
The bugs that this PR fix are:
 - new line immediatly after `[`
 - new line after `,`
 - trailing comma in lists

@evacchi can you put an eye before I merge?

### CODE REVIEW

File: shared/src/main/scala/org/akkajs/shocon/ConfigParser.scala [hunk 1]
```diff
@@ -50,7 +50,7 @@ object ConfigParser {
                             .map(Config.StringLiteral)
 
   // *** Parsing ***
-  val array: P[Seq[Config.Value]] = P( "[" ~/ jsonExpr.rep(sep=itemSeparator) ~ nlspace ~ "]")
+  val array: P[Seq[Config.Value]] = P( "[" ~ nlspace ~/ jsonExpr.rep(sep=itemSeparator) ~ nlspace ~ ",".? ~ nlspace ~ "]") // .log()
```
Comment (evacchi) [inline shared/src/main/scala/org/akkajs/shocon/ConfigParser.scala]: seems ok, maybe you want to remove `// log()`

**Comment by evan108108** [comment]
🤘 Looks great! Thanks for getting to this so fast!

**Comment by andreaTP** [comment]
I normally try to fix bugs if I know how to fix them :smile: 
I merge and I will release soon `0.4.1`
